### ISSUE TITLE
beta-testing: Updater Test - Issues

### ISSUE THREAD

**Issue by Twoure** [Twoure/UnSupportedServicesTools.bundle#2]
This thread is for reporting [Updater Test](https://github.com/Twoure/UnSupportedServicesTools.bundle/wiki/Beta---Testing#updater-test) issues.
- Include your Plex Media Server (PMS) version and host OS, as-well-as USS repo _branch_
- Include as much detail as you can in your observation as to what the issue may be
- Please upload `com.plexapp.plugins.unsupportedservicestools.log` and `com.plexapp.system.log` as an attachment or as a link with the logs hosted elsewhere.
- PMS Channel Logs location guide: https://support.plex.tv/hc/en-us/articles/201106148-Channel-Log-Files

**Comment by ObiDadKenobi** [comment]
Windows 2012 Server PMS OS FAILED (Dev Branch)
[com.plexapp.plugins.unsupportedservicestools.zip](https://github.com/Twoure/UnSupportedServicesTools.bundle/files/368154/com.plexapp.plugins.unsupportedservicestools.zip)
- WIndows 10/Chrome Client

**Comment by ObiDadKenobi** [comment]
The first test services link worked, the second http://vidspot.net/h144rvyo5mlz did not with the updatre

**Comment by Twoure** [comment]
Thanks @celestil, I forgot to add that I need to see the `com.plexapp.system.log` when a video fails to play.  The system log is where the issue will be logged since the USS is handled as system code.  If possible please upload the system log from the same time or please recreate the issue and upload both logs.

Thank you for helping.

**Comment by ObiDadKenobi** [comment]
I know it is verboten to change anything but I upgraded the PMS version when I redid this test. I continued from the original test URL which worked without issue and came up to the same problem when I changed to the DEV branch. Here are the logs you wanted
[com.plexapp.system.zip](https://github.com/Twoure/UnSupportedServicesTools.bundle/files/370300/com.plexapp.system.zip)

**Comment by ObiDadKenobi** [comment]
I would also like to add there is no way to change back to the previous version of the USS once you have updated to the dev version. You should add the capability to overwrite a dev version with the master version. Just a thought

**Comment by Twoure** [comment]
Thanks @celestil 

Your sys log showed me that my VidSpot code was incorrect.  It was set to allow direct stream/play but the host ties the final video URL to your PMS IP.  Just updated `dev` code to fix this.  Please use USST to check for an update (on the `dev` branch) and update, then test the vidspot link again.

From your logs it shows that the updated service code did register with the system, otherwise you would have gotten a pop-up saying that there is no VidSpot URL service code.

> I would also like to add there is no way to change back to the previous version of the USS once you have updated to the dev version. You should add the capability to overwrite a dev version with the master version.

Agreed.  This is something I will incorporate soon.  I would have spent time coding for it, but really wanted to know if the code worked at all for other platforms before perusing further development.

For now the USST checks the USS install directory, so you can delete the USS install, allowing for the USST to revert to the initial install button.  Then switch back to the `master` branch and preform the initial install.  Granted this is not optimal, and as such I will workout a better solution in the future.

**Comment by ObiDadKenobi** [comment]
How do you want report of a site failure on PrimeWire with this new code? Decided I would run a movie from briskfile.com and it failed.

**Comment by Twoure** [comment]
> How do you want report of a site failure on PrimeWire with this new code? Decided I would run a movie from briskfile.com and it failed.

**First:**
The [dev](https://github.com/Twoure/lmwt-kiss.bundle/tree/dev) _(or any version for that matter, mine or Pips)_ PrimeWire is _not_ setup to filter out dead host URLs.  So normally if a video does not play for that host, then it has been removed from the host site.  If the same host plays a different show/movie, then the code should be fine.  When in doubt, check the video within a normal browser before reporting an error (i.e. open the PrimeWire site within a web browser, find the offending video link and check that it works or fails).  PrimeWire is not good about removing dead links, and there is no reasonable way to check them within Plex's Framework.

**Second:**
If a host is refusing to play **New** video links (old links are susceptible to being offline) across multiple different videos, then report the issue within the [UnSupportedServices.bundle issues](https://github.com/Twoure/UnSupportedServices.bundle/issues).  Make sure to include the Plex Channel's log as-well-as the `com.plexapp.system.log`.

**Comment by Twoure** [comment]
Closing beta.

**Comment by ObiDadKenobi** [comment]
what happened to the primewire channel? Is there a way to fix it?
